
build:
  version: "3.0"

accounts:
  message: "Welcome to Accounts Service"
  contactDetails:
    email: "pandey@gmail.com"
    name: "Vivek Pandey"
  onCallSupport:
    - (+91) 1234567890
    - (+91) 9876543210