
build:
  version: "2.0"

cards:
  message: "Welcome to QA APIs for Cards Service"
  contactDetails:
    email: "vivek@gmail.com"
    name: "Aman Pandey"
  onCallSupport:
    - (+91) 1234567891
    - (+91) 9876543211