build:
  version: "1.0"

cards:
  message: "Welcome to Prod APIs for Cards Service"
  contactDetails:
    email: "vivrk@gmail.com"
    name: "Rohit Pandey"
  onCallSupport:
    - (+91) 1234567895
    - (+91) 9876543215