services:
#  accountsdb:
#    container_name: accountsdb
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_DATABASE: accountsdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config
#
#  loansdb:
#    container_name: loansdb
#    ports:
#      - "3308:3306"
#    environment:
#      MYSQL_DATABASE: loansdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config
#
#  cardsdb:
#    container_name: cardsdb
#    ports:
#      - "3309:3306"
#    environment:
#      MYSQL_DATABASE: cardsdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config

#  rabbit:
#    image: rabbitmq:3.13-management
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    extends:
#      file: common-config.yml
#      service: microservice-base-config
#    environment:
#      SPRING_RABBITMQ_HOST: "rabbit"

  configserver:
    image: "pandeyvivek007/configserver:s9"
    container_name: configserver-ms
    ports:
      - "8071:8071"
#    depends_on:
#      rabbit:
#        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "pandeyvivek007/eurekaserver:s9"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  gatewayserver:
    image: "pandeyvivek007/gatewayserver:s9"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
    #      cardsdb:
    #        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    #      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  accounts:
    image: "pandeyvivek007/accounts:s9"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
#      accountsdb:
#        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "pandeyvivek007/loans:s9"
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
#      loansdb:
#        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "pandeyvivek007/cards:s9"
    container_name: cards-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
#      cardsdb:
#        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  pandeyvivek007:
    driver: "bridge"